// const hints = {
//   q: "left pinky",
//   w: "left ring",
//   e: "left middle",
//   r: "left index",
//   t: "left index stretch",
//   y: "right index stretch",
//   u: "right index",
//   i: "right middle",
//   o: "right ring",
//   p: "right pinky",
//   a: "left pinky",
//   s: "left ring",
//   d: "left middle",
//   f: "left index",
//   g: "left index stretch",
//   h: "right index stretch",
//   j: "right index",
//   k: "right middle",
//   l: "right ring",
//   ";": "right thumb, right index",
//   ":": "left thumb, right index",
//   "/": "right thumb, left index stretch",
//   z: "left pinky",
//   x: "left ring",
//   c: "left middle",
//   v: "left index",
//   b: "left index stretch",
//   n: "right index stretch",
//   m: "right index",
//   ",": "right middle",
//   ".": "right ring",
//   "`": "right thumb, left index stretch",
//   1: "right thumb, left pinky",
//   2: "right thumb, left ring",
//   3: "right thumb, left middle",
//   4: "right thumb, left index",
//   5: "right thumb, left index stretch",
//   6: "right thumb, right index stretch",
//   7: "right thumb, right index",
//   8: "right thumb, right middle",
//   9: "right thumb, right ring",
//   0: "right thumb, right pinky",
//   "~": "left thumb, left index stretch",
//   "!": "left thumb, left pinky",
//   "@": "left thumb, left ring",
//   "#": "left thumb, left middle",
//   $: "left thumb, left index",
//   "%": "left thumb, left index stretch",
//   "^": "left thumb, right index stretch",
//   "&": "left thumb, right index",
//   "*": "left thumb, right middle",
//   "(": "left thumb, right ring",
//   ")": "left thumb, right pinky",
//   Backspace: "right pinky",
//   Enter: "right pinky",
//   "-": "right thumb, left index",
//   "=": "right thumb, left middle",
//   "[": "right thumb, right middle",
//   "]": "right thumb, right ring",
//   "?": "left thumb, left index stretch",
//   _: "left thumb, left index",
//   "+": "left thumb, left middle",
//   "{": "left thumb, right middle",
//   "}": "left thumb, right ring",
//   "\\": "right thumb, left index",
//   "|": "left thumb, left index",
//   "<": "shift right middle",
//   ">": "shift right ring",
//   "'": "right thumb, right index stretch",
//   '"': "left thumb, right index stretch",
//   ArrowUp: "right/left thumb, right middle",
//   ArrowDown: "right/left thumb, right index",
//   ArrowLeft: "right/left thumb, right index stretch",
//   ArrowRight: "right/left thumb, right ring",
//   Meta: "left thumb",
//   Alt: "left thumb",
//   Control: "left pinky"
// };

const hints = {
  q: "left pinky",
  w: "left ring",
  e: "left middle",
  r: "left index",
  t: "left index stretch",
  y: "right index stretch",
  u: "right index",
  i: "right middle",
  o: "right ring",
  p: "right pinky",
  a: "left pinky",
  s: "left ring",
  d: "left middle",
  f: "left index",
  g: "left index stretch",
  h: "right index stretch",
  j: "right index",
  k: "right middle",
  l: "right ring",
  ";": "right pinky",
  ":": "right pinky",
  "/": "right pinky",
  z: "left pinky",
  x: "left ring",
  c: "left middle",
  v: "left index",
  b: "left index stretch",
  n: "right index stretch",
  m: "right index",
  ",": "right middle",
  ".": "right ring",
  "`": "left pinky stretch",
  1: "left pinky",
  2: "left ring",
  3: "left middle",
  4: "left index",
  5: "left index stretch",
  6: "right index stretch",
  7: "right index",
  8: "right middle",
  9: "right ring",
  0: "right pinky",
  "~": "left pinky stretch",
  "!": "left pinky",
  "@": "left ring",
  "#": "left middle",
  $: "left index",
  "%": "left index stretch",
  "^": "right index stretch",
  "&": "right index",
  "*": "right middle",
  "(": "right ring",
  ")": "right pinky",
  Backspace: "right pinky stretch",
  Enter: "right pinky stretch",
  "-": "right pinky stretch",
  "=": "right pinky stretch",
  "[": "right pinky stretch",
  "]": "right pinky stretch",
  "?": "right pinky",
  _: "right pinky stretch",
  "+": "right pinky stretch",
  "{": "right pinky stretch",
  "}": "right pinky stretch",
  "\\": "right pinky stretch",
  "|": "right pinky stretch",
  "<": "right middle",
  ">": "right ring",
  "'": "right pinky stretch",
  '"': "right pinky stretch",
};

export default hints;
